import { TEAM_KEYS, movement, wantsSprint, isEditing, ActionQueue, installLifecycle } from '../shared/controls.js';
let frameId;
function fatal(e){cancelAnimationFrame(frameId);playing=false;$('start').disabled=true;$('error').hidden=false;console.error(e)}
function assist(){$('assist-toggle').textContent=`Movement help: ${game.assisted?'on':'off'}`;$('assist-toggle').setAttribute('aria-pressed',String(game.assisted))}
import{WaterPoloGame,STEP}from'./simulation.js';const $=id=>document.getElementById(id),keys=new Set(),coarse=matchMedia('(pointer:coarse)').matches;let game=new WaterPoloGame(),view,playing=false,last=0,acc=0,actions=new ActionQueue(),moveTouch={x:0,z:0},sound=false,audio;const dialogs=[$('help-dialog'),$('pause-dialog'),$('result-dialog')],paused=()=>dialogs.some(d=>d.open);
function tone(type){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type='triangle';o.frequency.setValueAtTime(type==='goal'?680:220,t);o.frequency.exponentialRampToValueAtTime(type==='goal'?980:90,t+.18);g.gain.setValueAtTime(.06,t);g.gain.exponentialRampToValueAtTime(.0001,t+.22);o.connect(g);g.connect(audio.destination);o.start();o.stop(t+.24)}catch{sound=false}}
function clear(){keys.clear();actions.clear();moveTouch={x:0,z:0};$('joystick-thumb').style.transform=''}function ui(){document.body.classList.toggle('playing',playing);for(const id of['lobby','court-note','lobby-footer'])$(id).hidden=playing;for(const id of['hud','controls','pause','player-label','shot-clock'])$(id).hidden=!playing;$('touch-controls').hidden=!playing||!(coarse||innerWidth<650);view.setLobby(!playing)}
function start(){dialogs.forEach(d=>d.close());game=new WaterPoloGame({duration:$('duration').value,difficulty:$('difficulty').value,assisted:$('assist').checked,seed:Date.now()%2147483647});playing=true;acc=0;clear();ui();assist();$('court').tabIndex=0;$('court').focus()}function quit(){dialogs.forEach(d=>d.close());playing=false;game=new WaterPoloGame();clear();ui()}function input(){const x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+moveTouch.x,z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+moveTouch.z;return{...movement(x,z,view.camera),sprint:wantsSprint(keys,moveTouch),action:actions.take(),aim:game.aim}}
function hud(){$('blue-score').textContent=game.goals[0];$('red-score').textContent=game.goals[1];$('quarter').textContent='Q'+game.quarter;const remain=Math.max(0,Math.ceil(game.duration-game.elapsed));$('clock').textContent=`${String(Math.floor(remain/60)).padStart(2,'0')}:${String(remain%60).padStart(2,'0')}`;$('shot-clock').querySelector('b').textContent=Math.max(0,Math.ceil(game.possession));$('callout').hidden=!playing||game.stage==='play'||game.stage==='over';$('callout-title').textContent=game.message;$('callout-detail').textContent=game.stage==='goal'?'Back to halfway':game.stage==='quarter'?'Next quarter starts shortly':'The ball is live'}
function frame(now){frameId=requestAnimationFrame(frame);const dt=Math.min((now-last)/1000||0,.06);last=now;if(playing&&!paused()){acc=Math.min(acc+dt,STEP*8);while(acc>=STEP){game.step(STEP,input());acc-=STEP}for(const e of game.drainEvents()){tone(e.type);if(e.type==='fulltime'){$('result-title').textContent=game.goals[0]>game.goals[1]?'The pool is yours.':game.goals[0]===game.goals[1]?'Honours even.':'Back in for another?';$('result-score').textContent=game.goals.join(' : ');$('result-stats').textContent=`Shots ${game.stats.shots.join(' : ')} · Saves ${game.stats.saves.join(' : ')} · Steals ${game.stats.steals.join(' : ')}`;$('result-dialog').showModal();clear()}}hud()}else acc=0;const p=view.render(game,dt,now/1000);$('player-label').style.left=p.x+'px';$('player-label').style.top=p.y+'px'}
$('start').onclick=()=>view&&start();$('restart').onclick=start;$('rematch').onclick=start;$('quit').onclick=quit;$('result-quit').onclick=quit;$('resume').onclick=()=>$('pause-dialog').close();$('pause').onclick=()=>{if(playing&&!paused()&&game.stage!=='over'){clear();$('pause-dialog').showModal()}};$('help').onclick=()=>{clear();$('help-dialog').showModal()};$('reload').onclick=()=>location.reload();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));tone('throw')};$('camera').onclick=()=>{if(!view)return;view.mode=view.mode==='broadcast'?'tactical':'broadcast';$('camera').textContent='Camera: '+view.mode};$('assist-toggle').onclick=()=>{game.assisted=!game.assisted;assist()};
const map={...TEAM_KEYS,KeyE:'lead',KeyK:'lead',KeyL:'lead',KeyF:'steal'};window.addEventListener('keydown',e=>{if(isEditing(e.target))return;if(e.code==='Escape'||e.code==='KeyP'){if(playing&&!paused())$('pause').click();return}if(e.key==='?'&&!paused())$('help').click();if(!playing||paused())return;if(map[e.code]||e.code.startsWith('Arrow'))e.preventDefault();keys.add(e.code);if(!e.repeat&&map[e.code])actions.push(map[e.code])});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('resize',()=>{if(view){view.resize();ui()}});$('court').addEventListener('pointermove',e=>{if(view&&playing&&!paused()&&e.pointerType!=='touch')game.aim=view.aimAt(e.clientX,e.clientY)});$('court').addEventListener('pointerdown',e=>{if(view&&playing&&!paused()){e.preventDefault();$('court').focus();game.aim=view.aimAt(e.clientX,e.clientY);if(e.pointerType!=='touch')actions.push(e.button===2?'lead':'pass')}});$('court').oncontextmenu=e=>e.preventDefault();document.querySelectorAll('[data-action]').forEach(b=>b.onpointerdown=e=>{e.preventDefault();if(playing&&!paused())actions.push(b.dataset.action)});
let jid=null;function stick(e){if(e.pointerId!==jid)return;const r=$('joystick').getBoundingClientRect(),q=r.width*.34;let x=(e.clientX-r.left-r.width/2)/q,z=(e.clientY-r.top-r.height/2)/q,n=Math.max(1,Math.hypot(x,z));x/=n;z/=n;moveTouch={x,z};$('joystick-thumb').style.transform=`translate(${x*q}px,${z*q}px)`}$('joystick').onpointerdown=e=>{jid=e.pointerId;$('joystick').setPointerCapture(jid);stick(e)};$('joystick').onpointermove=stick;for(const n of['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(n,e=>{if(e.pointerId===jid){jid=null;moveTouch={x:0,z:0};$('joystick-thumb').style.transform=''}});
$('start').disabled=true;
installLifecycle({canvas:$('court'),dialogs,clear,active:()=>playing&&!paused()&&game.stage!=='over',pause:()=>$('pause').click(),fatal});
try{const{WaterPoloView}=await import('./render.js');await document.fonts.ready;view=new WaterPoloView($('court'));$('start').disabled=false;requestAnimationFrame(frame)}catch(e){fatal(e)}
