import{POOL,FORMATION,clamp,distance,attackDirection,classifyBall,shotClockExpired}from'./rules.js';
export const STEP=1/60;
export function seededRandom(seed=17){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let n=Math.imul(seed^seed>>>15,1|seed);n=n+Math.imul(n^n>>>7,61|n)^n;return((n^n>>>14)>>>0)/4294967296}};
export class WaterPoloGame{
 constructor({duration=240,difficulty='club',assisted=true,seed=17}={}){this.duration=Number(duration);this.difficulty=difficulty;this.assisted=assisted;this.random=seededRandom(seed);this.players=Array.from({length:14},(_,id)=>({id,team:id<7?0:1,keeper:id%7===0,x:0,z:0,vx:0,vz:0,facing:0,cooldown:0,stroke:0,stamina:1}));this.ball={x:0,y:.25,z:0,vx:0,vy:0,vz:0,owner:null};this.goals=[0,0];this.stats={shots:[0,0],passes:[0,0],saves:[0,0],steals:[0,0]};this.quarter=1;this.elapsed=0;this.time=0;this.possession=30;this.stage='start';this.timer=1.5;this.message='Swim-off';this.controlled=4;this.events=[];this.restart(0,'swim-off')}
 d(t){return attackDirection(t)}emit(type,data={}){this.events.push({type,...data})}drainEvents(){return this.events.splice(0)}
 restart(team,reason='restart'){const d=this.d(team);this.players.forEach(p=>{const n=p.id%7;if(p.keeper){p.x=0;p.z=-d*13.7}else{const f=FORMATION[n-1];p.x=f[0];p.z=f[1]*(team===0?1:-1)}p.vx=p.vz=0;p.cooldown=0});const p=this.players[team*7+4];p.x=0;p.z=0;this.ball={x:p.x,y:.28,z:p.z,vx:0,vy:0,vz:0,owner:p.id};this.possession=30;this.controlled=team===0?p.id:this.controlled;this.stage='restart';this.timer=reason==='swim-off'?1.2:.8;this.message=reason==='goal'?'Back to halfway':'Swim-off'}
 move(p,target,speed,dt){const dx=target.x-p.x,dz=target.z-p.z,n=Math.hypot(dx,dz)||1;p.vx=dx/n*speed;p.vz=dz/n*speed;p.x=clamp(p.x+p.vx*dt,-9.5,9.5);p.z=clamp(p.z+p.vz*dt,-14.3,14.3);if(n>.2)p.facing=Math.atan2(p.vx,p.vz);p.stroke+=dt*speed}
 target(p,kind,aim){const mates=this.players.filter(q=>q.team===p.team&&!q.keeper&&q.id!==p.id),d=this.d(p.team);if(aim){mates.sort((a,b)=>distance(a,aim)-distance(b,aim));return mates[0]}return mates.sort((a,b)=>(b.z-a.z)*d+distance(a,p)*.15)[0]}
 throw(p,kind='pass',aim=null,power=.7){if(this.ball.owner!==p.id)return false;const d=this.d(p.team),shoot=kind==='shoot',q=shoot?null:this.target(p,kind,aim),tx=shoot?(aim?clamp(aim.x,-1.35,1.35):(this.random()-.5)*2.4):q.x,tz=shoot?d*16:q.z+d*(kind==='lead'?2.2:0),dx=tx-p.x,dz=tz-p.z,n=Math.hypot(dx,dz)||1,speed=shoot?15+power*7:kind==='lead'?13:11;this.ball={x:p.x+dx/n*.65,y:.65,z:p.z+dz/n*.65,vx:dx/n*speed,vy:shoot?2.8:2,vz:dz/n*speed,owner:null};p.cooldown=.45;this.lastTouch=p.team;this.lastThrow=p.id;this.throwTime=this.time;this.stats[shoot?'shots':'passes'][p.team]++;this.stage='play';this.emit('throw',{team:p.team,kind});return true}
 gain(p){this.ball.owner=p.id;this.ball.vx=this.ball.vy=this.ball.vz=0;this.lastTouch=p.team;this.possession=30;p.cooldown=.3;if(p.team===0&&!p.keeper)this.controlled=p.id;this.emit('possession',{team:p.team})}
 steal(p){const owner=this.players[this.ball.owner];if(!owner||owner.team===p.team||p.cooldown>0||distance(p,owner)>1.45)return false;p.cooldown=1;this.stats.steals[p.team]++;this.gain(p);this.emit('steal',{team:p.team});return true}
 goal(team){this.goals[team]++;this.stage='goal';this.timer=2.4;this.scoring=team;this.message=team===0?'WHAT A GOAL!':'District scores';this.emit('goal',{team})}
 loose(dt){const b=this.ball,oldZ=b.z;b.vy-=5.5*dt;b.x+=b.vx*dt;b.z+=b.vz*dt;b.y+=b.vy*dt;if(b.y<.22){b.y=.22;b.vy=Math.abs(b.vy)*.18;b.vx*=Math.exp(-1.4*dt);b.vz*=Math.exp(-1.4*dt)}const result=classifyBall(b);if(result){if(result.type==='goal')this.goal(result.team);else this.turnover(result.team??1-this.lastTouch);return}if(Math.abs(oldZ)<POOL.halfLength&&Math.abs(b.z)>=POOL.halfLength&&Math.abs(b.x)<POOL.goalHalfWidth){this.goal(b.z<0?0:1);return}for(const p of [...this.players].sort((a,c)=>distance(a,b)-distance(c,b))){if(p.id===this.lastThrow&&this.time-this.throwTime<.35)continue;const range=p.keeper?1.25:.8;if(distance(p,b)<range&&b.y<1.25){if(p.keeper&&p.team!==this.lastTouch){this.stats.saves[p.team]++;this.emit('save',{team:p.team})}this.gain(p);break}}
 }
 turnover(team){const p=this.players[team*7],d=this.d(team);this.ball={x:p.x,y:.4,z:p.z-d*.6,vx:0,vy:0,vz:0,owner:p.id};this.possession=30;this.stage='restart';this.timer=.65;this.message='Turnover';if(team===0)this.controlled=1;this.emit('whistle',{team})}
 updatePlayers(dt,input){const carrier=this.ball.owner===null?null:this.players[this.ball.owner];for(const p of this.players){p.cooldown=Math.max(0,p.cooldown-dt);const human=p.id===this.controlled,d=this.d(p.team),attack=carrier?.team===p.team;let speed=p.team===0?3.15:{casual:2.45,club:2.85,pro:3.15}[this.difficulty];if(human&&input.sprint&&p.stamina>.05){speed*=1.35;p.stamina-=dt*.12}else p.stamina=Math.min(1,p.stamina+dt*.07);if(p.keeper){this.move(p,{x:clamp(this.ball.x*.45,-1.3,1.3),z:-d*13.65},2.6,dt);continue}if(human&&(input.moveX||input.moveZ)){const n=Math.hypot(input.moveX,input.moveZ);this.move(p,{x:p.x+input.moveX/n,z:p.z+input.moveZ/n},speed,dt)}else if(human&&!this.assisted){p.vx=p.vz=0}else{const f=FORMATION[p.id%7-1],target=attack?{x:f[0]+this.ball.x*.25,z:clamp(f[1]*-d+this.ball.z*.2,-11.8,11.8)}:{x:f[0]*.85,z:clamp((f[1]-3)*d+this.ball.z*.15,-12,12)};if(!carrier&&distance(p,this.ball)<distance(this.players[p.team*7+1],this.ball)+1)this.move(p,this.ball,speed,dt);else if(carrier&&carrier.team!==p.team&&distance(p,carrier)<5)this.move(p,carrier,speed,dt);else this.move(p,target,speed,dt)}if(carrier?.id===p.id&&!human&&p.cooldown<=0){const goal=distance(p,{x:0,z:d*15});if(goal<8)this.throw(p,'shoot',null,.45+this.random()*.45);else if(this.random()<dt*.8)this.throw(p,this.random()<.3?'lead':'pass')}if(carrier&&carrier.team!==p.team&&!human&&distance(p,carrier)<1.3)this.steal(p)}}
 step(dt,input={}){if(this.stage==='over')return;this.time+=dt;if(this.stage==='goal'){this.timer-=dt;if(this.timer<=0)this.restart(1-this.scoring,'goal');return}if(this.stage==='quarter'){this.timer-=dt;if(this.timer<=0)this.restart(this.quarter%2?0:1,'swim-off');return}if(this.stage==='restart'){this.timer-=dt;if(this.timer<=0){this.stage='play';if(this.players[this.ball.owner].team===1)this.throw(this.players[this.ball.owner],'pass')}return}if(this.stage!=='play')return;this.elapsed+=dt;this.possession-=dt;if(shotClockExpired(this.possession)){const ownerTeam=this.ball.owner===null?this.lastTouch:this.players[this.ball.owner].team;this.turnover(1-ownerTeam);return}const boundary=this.duration/4*this.quarter;if(this.elapsed>=boundary){if(this.quarter===4){this.stage='over';this.emit('fulltime',{goals:[...this.goals]});return}this.quarter++;this.stage='quarter';this.timer=2;this.message=`End of quarter ${this.quarter-1}`;this.emit('quarter');return}const h=this.players[this.controlled];if(input.action==='steal')this.steal(h);if(['pass','lead','shoot'].includes(input.action)&&this.ball.owner===h.id)this.throw(h,input.action,input.aim,input.power??.7);this.updatePlayers(dt,input);if(this.ball.owner!==null){const p=this.players[this.ball.owner];this.ball.x=p.x+Math.sin(p.facing)*.52;this.ball.z=p.z+Math.cos(p.facing)*.52;this.ball.y=.52+Math.sin(this.time*7)*.05}else this.loose(dt)}
}
