import { installViews } from '../shared/cameras.js';
import { installTouchAim, observeSurface } from '../shared/touch.js';
import { sportsMouse } from '../shared/sports-mouse.js';
let mouse;
import { isEditing, installLifecycle } from '../shared/controls.js';
let frameId;
function fatal(e){playing=false;mouse?.cancel();keys.clear();cancelAnimationFrame(frameId);playing=false;$('start').disabled=true;$('error').hidden=false;console.error(e)}
function cycleClub(){if(playing&&!paused()&&game.stage==='aim'){const clubs=Object.keys(CLUBS);game.club=clubs[(clubs.indexOf(game.club)+1)%clubs.length];sync()}}
import {GolfGame,STEP,CLUBS,clamp} from './simulation.js';
const $=id=>document.getElementById(id);let game=new GolfGame(),view,playing=false,last=0,acc=0,sound=false,audio,loaded=-1;const keys=new Set(),dialogs=[$('help-dialog'),$('pause-dialog'),$('result-dialog')];const paused=()=>dialogs.some(d=>d.open);
function tone(type){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.type='triangle';o.frequency.setValueAtTime(type==='holed'?740:type==='penalty'?120:260,t);o.frequency.exponentialRampToValueAtTime(type==='holed'?1100:80,t+.25);g.gain.setValueAtTime(.07,t);g.gain.exponentialRampToValueAtTime(.0001,t+.3);o.connect(g);g.connect(audio.destination);o.start();o.stop(t+.32);}catch{sound=false;}}
function score(n){return n===0?'E':n>0?'+'+n:String(n)}
function sync(){if(game.holeIndex!==loaded){loaded=game.holeIndex;view.load(game.hole);}$('hole-name').textContent=game.hole.name.toUpperCase();$('hole-number').textContent=game.holeIndex+1;$('hole-par').textContent=game.hole.par;$('round-score').textContent=score(game.total-game.par);$('stroke-label').textContent=`Stroke ${game.strokes+1}`;$('distance').textContent=Math.round(game.distance);$('lie-label').textContent=game.lie.toUpperCase();$('club').value=game.club;$('power').value=Math.round(game.power*100);$('power-output').textContent=Math.round(game.power*100)+'%';const ws=Math.hypot(game.wind.x,game.wind.z);$('wind-speed').textContent=Math.round(ws)+' m/s';$('wind-arrow').style.transform=`rotate(${Math.atan2(game.wind.x,-game.wind.z)}rad)`;$('shot-panel').classList.toggle('disabled',game.stage!=='aim');$('hit').disabled=game.stage!=='aim';$('club').disabled=$('power').disabled=game.stage!=='aim';$('shot-status').textContent=game.stage==='flight'?'Ball in flight…':game.message;$('callout').hidden=!playing||!['holed'].includes(game.stage);$('callout-title').textContent=game.message;$('callout-detail').textContent=game.holeIndex+1>=game.count?'Round complete':'Write it down, then move on';$('next').hidden=game.stage!=='holed';}
function ui(){document.body.classList.toggle('playing',playing);for(const id of ['lobby','court-note','lobby-footer'])$(id).hidden=playing;for(const id of ['hud','shot-panel','controls','pause'])$(id).hidden=!playing;view.setLobby(!playing);sync();}
function start(){mouse?.cancel();keys.clear();dialogs.forEach(d=>d.close());game=new GolfGame({holes:$('holes').value,wind:$('wind').value});loaded=-1;playing=true;acc=0;ui();$('court').tabIndex=0;$('court').focus();}
function quit(){mouse?.cancel();keys.clear();dialogs.forEach(d=>d.close());playing=false;game=new GolfGame();loaded=-1;ui();$('start').focus();}
function finish(){const relative=game.total-game.par;$('result-title').textContent=relative<0?'You filled the margins with birdies.':relative===0?'Right on the line.':'Every round leaves a story.';$('result-score').textContent=score(relative);$('result-stats').textContent=`${game.total} strokes · Par ${game.par} · ${game.totalPenalties} penalty ${game.totalPenalties===1?'stroke':'strokes'}`;$('result-dialog').showModal();}
function next(){if(!playing||paused()||game.stage!=='holed')return;if(game.holeIndex+1>=game.count){game.stage='over';finish();}else{game.next();sync();}}
function animate(now){frameId=requestAnimationFrame(animate);mouse?.update(now);const dt=Math.min((now-last)/1000||0,.06);last=now;if(playing&&!paused()){acc=Math.min(acc+dt,STEP*8);while(acc>=STEP){game.step(STEP);acc-=STEP;}for(const e of game.drainEvents())tone(e.type);let da=((keys.has('KeyD')||keys.has('ArrowRight'))?1:0)-((keys.has('KeyA')||keys.has('ArrowLeft'))?1:0),dp=((keys.has('KeyW')||keys.has('ArrowUp'))?1:0)-((keys.has('KeyS')||keys.has('ArrowDown'))?1:0);if(!mouse?.charging&&game.stage==='aim'&&(da||dp)){game.angle+=da*dt*.8*(view.views?.mode==='first'?-1:1);game.power=clamp(game.power+dp*dt*.45,.05,1);sync();}else sync();}else acc=0;view.render(game,dt,now/1000);}
$('start').onclick=()=>view&&start();$('hit').onclick=()=>{if(playing&&!paused())game.shoot()};$('next').onclick=next;$('restart').onclick=start;$('rematch').onclick=start;$('quit').onclick=quit;$('result-quit').onclick=quit;$('resume').onclick=()=>$('pause-dialog').close();$('pause').onclick=()=>{if(playing&&!paused()&&game.stage!=='over'){mouse?.cancel();keys.clear();$('pause-dialog').showModal();}};$('help').onclick=()=>{mouse?.cancel();keys.clear();$('help-dialog').showModal()};$('reload').onclick=()=>location.reload();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('club').onchange=e=>{if(!playing||paused()||game.stage!=='aim')return;game.club=e.target.value;sync();};$('power').oninput=e=>{if(!playing||paused()||game.stage!=='aim')return;game.power=e.target.value/100;sync();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));tone('swing');};$('camera').onclick=()=>{if(!view)return;view.follow=!view.follow;$('camera').textContent=`Camera: ${view.follow?'follow':'overview'}`;};
window.addEventListener('keydown',e=>{if(isEditing(e.target))return;if(e.code==='Escape'||e.code==='KeyP'){if(playing&&!paused()&&game.stage!=='over'){mouse?.cancel();keys.clear();$('pause-dialog').showModal();}return;}if(e.key==='?'&&!paused())$('help').click();if(!playing||paused())return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyE'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='Space'&&!e.repeat)game.shoot();if(e.code==='KeyE'&&!e.repeat)cycleClub();if(game.stage==='aim'&&/^Digit[1-4]$/.test(e.code)){game.club=['driver','iron','wedge','putter'][Number(e.code.slice(-1))-1];sync();}});window.addEventListener('keyup',e=>keys.delete(e.code));installTouchAim({ canvas: $('court'), active: () => playing && !paused() && game.stage === 'aim' && !mouse?.charging, aim: event => { if (!view) return; const point = view.aimAt(event.clientX, event.clientY); if (point) game.angle = Math.atan2(point.x - game.ball.x, point.z - game.ball.z); } });
observeSurface($('court'), () => view?.resize());
window.addEventListener('resize',()=>view?.resize());
$('court').addEventListener('pointermove',e=>{if(e.pointerType==='touch'||mouse?.charging||!playing||paused()||game.stage!=='aim')return;const p=view.aimAt(e.clientX,e.clientY);if(p)game.angle=Math.atan2(p.x-game.ball.x,p.z-game.ball.z);});$('court').addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||mouse?.charging||!view||!playing||paused()||game.stage!=='aim')return;e.preventDefault();$('court').focus();const p=view.aimAt(e.clientX,e.clientY);if(p)game.angle=Math.atan2(p.x-game.ball.x,p.z-game.ball.z);});
$('start').disabled=true;
$('court').addEventListener('contextmenu',e=>e.preventDefault());
installLifecycle({canvas:$('court'),dialogs,clear:()=>{mouse?.cancel();keys.clear();acc=0},active:()=>playing&&!paused()&&game.stage!=='over',pause:()=>$('pause').click(),fatal});
mouse=sportsMouse({canvas:$('court'),game:()=>game,active:()=>playing&&!paused()&&game.stage==='aim',context:g=>g.holeIndex+':'+g.strokes+':'+g.club+':'+g.stage,lockAim:true,secondary:cycleClub,previewPower:p=>game.power=p,restorePower:()=>{const g=game,p=g.power;return()=>g.power=p},fire:p=>{game.power=p;game.shoot()}});

try{const {GolfView}=await import('./render.js');await document.fonts.ready;view=new GolfView($('court')); installViews(view, 'golf', () => { mouse?.cancel(); keys.clear(); }, { active: () => playing && !paused(), canAim: () => game.stage === 'aim', charging: () => mouse?.charging });$('start').disabled=false;view.load(game.hole);requestAnimationFrame(animate);}catch(e){fatal(e);}
