import { inkSurface, penMaterial, outlineMeshes } from '../shared/ink.js';
import * as THREE from '../vendor/three.module.min.js'; import {R,clamp} from './simulation.js';
const BLUE=0x2a42ad,RED=0xc94b59,PAPER=0xf7f4e9,GREEN=0x607b63,SAND=0xd2b96b,WATER=0x789dc7,V=(x,y,z)=>new THREE.Vector3(x,y,z);
const mat=inkSurface;
function disposeGroup(group){group.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of(Array.isArray(o.material)?o.material:[o.material]))m.dispose()}});group.clear()}
export class GolfView{
 constructor(canvas){this.canvas=canvas;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.setClearColor(PAPER,0);this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(41,1,.1,700);this.ray=new THREE.Raycaster();this.ground=new THREE.Plane(V(0,1,0),0);this.point=V();this.follow=true;this.lobby=true;this.course=new THREE.Group();this.scene.add(this.course);this.trail=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:BLUE,dashSize:2,gapSize:1,transparent:true,opacity:.7}));this.scene.add(this.trail);this.ball=new THREE.Mesh(new THREE.SphereGeometry(.7,14,10),mat(PAPER));this.ball.add(new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.SphereGeometry(.71,10,7)),new THREE.LineBasicMaterial({color:BLUE})));this.scene.add(this.ball);this.shadow=new THREE.Mesh(new THREE.CircleGeometry(.75,24),mat(BLUE,.17));this.shadow.rotation.x=-Math.PI/2;this.scene.add(this.shadow);this.golfer=this.player();outlineMeshes(this.golfer);this.scene.add(this.golfer);this.pin=new THREE.Group();this.scene.add(this.pin);this.resize();}
 player(){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.3,.65,3,8),mat(BLUE));body.position.y=1.35;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.27,10,7),mat(PAPER));head.position.y=2.15;g.add(head);head.add(new THREE.LineSegments(new THREE.EdgesGeometry(head.geometry),new THREE.LineBasicMaterial({color:BLUE})));for(const x of [-.17,.17]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.08,.08,.8,7),mat(BLUE));leg.position.set(x,.48,0);g.add(leg);}const club=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,1.8,6),mat(RED));club.position.set(.7,1,.25);club.rotation.z=-.35;g.add(club);g.userData.club=club;return g;}
 ellipse(e,color,opacity=.45){const m=new THREE.Mesh(new THREE.CircleGeometry(1,40),color===WATER?mat(color,opacity):penMaterial(color,opacity*.3));m.rotation.x=-Math.PI/2;m.scale.set(e[2],e[3],1);m.position.set(e[0],color===GREEN?.065:color===SAND?.055:.045,e[1]);this.course.add(m);}
 load(h){disposeGroup(this.course);this.lastPreview=null;const ground=new THREE.Mesh(new THREE.PlaneGeometry(150,Math.max(300,h.tee.z-h.cup.z+100)),penMaterial(GREEN,.025));ground.rotation.x=-Math.PI/2;ground.position.z=(h.tee.z+h.cup.z)/2;this.course.add(ground);for(let i=0;i<h.route.length-1;i++){const a=h.route[i],b=h.route[i+1],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz),f=new THREE.Mesh(new THREE.PlaneGeometry(25,len+12),penMaterial(GREEN,.09));f.rotation.x=-Math.PI/2;f.rotation.z=-Math.atan2(dx,dz);f.position.set((a[0]+b[0])/2,.02,(a[1]+b[1])/2);this.course.add(f);}h.water.forEach(e=>this.ellipse(e,WATER,.5));h.sand.forEach(e=>this.ellipse(e,SAND,.6));this.ellipse([h.cup.x,h.cup.z,h.green,h.green],GREEN,.5);const cup=new THREE.Mesh(new THREE.CircleGeometry(.58,20),mat(BLUE));cup.rotation.x=-Math.PI/2;cup.position.set(h.cup.x,.08,h.cup.z);this.course.add(cup);disposeGroup(this.pin);const pole=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,5,6),mat(RED));pole.position.y=2.5;this.pin.add(pole);const flag=new THREE.Mesh(new THREE.PlaneGeometry(1.7,.85),mat(RED,.85));flag.position.set(.85,4.45,0);this.pin.add(flag);this.pin.position.set(h.cup.x,0,h.cup.z);for(let i=0;i<34;i++){const z=h.cup.z-35+i*9,x=(i%2?62:-62);const tree=new THREE.Mesh(new THREE.ConeGeometry(2.2+(i%3),5+(i%4),7),mat(i%5===0?RED:BLUE,.18));tree.position.set(x+(i%4)*3,2.5,z);this.course.add(tree);}this.setLobby(this.lobby);}
 setLobby(v){this.lobby=v;this.resize();}
 resize(){this.renderer.setSize(innerWidth,innerHeight,false);this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();}
 aimAt(x,y){this.ray.setFromCamera({x:x/innerWidth*2-1,y:1-y/innerHeight*2},this.camera);if(!this.ray.ray.intersectPlane(this.ground,this.point))return null;return{x:this.point.x,z:this.point.z};}
 render(g,dt,t){const b=g.ball;this.ball.position.set(b.x,b.y+.45,b.z);this.ball.rotation.x+=dt*b.vz*.3;this.shadow.position.set(b.x,.07,b.z);this.shadow.scale.setScalar(1+b.y*.06);this.golfer.visible=g.stage!=='holed';const stance=g.stage==='flight'?g.lastSafe:b;this.golfer.position.set(stance.x,0,stance.z+1.6);this.golfer.rotation.y=g.angle;this.golfer.userData.club.rotation.z=g.stage==='flight'?-.35-Math.sin(Math.min(g.shotTime/.45,1)*Math.PI)*2:-.35;const preview=g.stage==='aim'?g.preview():null;this.trail.visible=!!preview;if(preview&&preview!==this.lastPreview){this.lastPreview=preview;this.trail.geometry.dispose();this.trail.geometry=new THREE.BufferGeometry().setFromPoints(preview.path.map(p=>V(p.x,p.y+.25,p.z)));this.trail.computeLineDistances();}const overview=this.lobby||!this.follow;const focus=overview?V((g.hole.tee.x+g.hole.cup.x)/2,0,(g.hole.tee.z+g.hole.cup.z)/2):V(b.x,0,b.z);const d=overview?Math.max(190,(g.hole.tee.z-g.hole.cup.z)*1.1):g.stage==='flight'&&this.follow?70:56;this.camera.position.lerp(focus.clone().add(V(d*.52,d*.58,d*.6)),1-Math.exp(-dt*4));this.camera.lookAt(focus);this.renderer.render(this.scene,this.camera);}
}
